const ActivityData = [
    {
        id: "s65rs4ma23",
        code: "CPE001",
        status: "open",
        name: "รถไฟเหาะ",
        image: "https://www.changtrixget.com/wp-content/uploads/2018/09/superman-krypton-coaster.jpg",
        waitingTime: 3,
        size: 20,
        duration: 5,
        star: 12,
        rating: 5,
    },
    {
        id: "f56s4rt1fd",
        code: "CPE002",
        status: "open",
        name: "ชิงช้าสวรรค์",
        size: 50,
        duration: 10,
        star: 8,
        rating: 4,
    },
    {
        id: "bs6t42as42",
        code: "CPE003",
        status: "open",
        name: "บ้านผีสิง",
        size: 30,
        duration: 10,
        star: 8,
        rating: 4,
    },
    {
        id: "sb5te64a21",
        code: "CPE004",
        status: "open",
        name: "ปราสาทยักษ์",
        size: 30,
        duration: 10,
        star: 6,
        rating: 4,
    },
    {
        id: "srt6542xz1",
        code: "CPE005",
        status: "open",
        name: "ทอร์นาโด",
        size: 12,
        duration: 5,
        star: 6,
        rating: 3,
    },
    {
        id: "2d1ytn51a2",
        code: "CPE006",
        status: "open",
        name: "ท่องกาแล็กซี่",
        size: 10,
        duration: 8,
        star: 10,
        rating: 4,
    },
    {
        id: "5e41vbt4h8",
        code: "CPE007",
        status: "closed",
        name: "ทะยานเมฆา",
        size: 20,
        duration: 10,
        star: 10,
        rating: 4,
    },
    {
        id: "dn685t24d4",
        code: "CPE008",
        status: "temporarily closed",
        name: "ทะยานเมฆา",
        size: 20,
        duration: 10,
        star: 10,
        rating: 4,
    },
    {
        id: "s65rs4ma23",
        code: "CPE001",
        status: "open",
        name: "รถไฟเหาะ",
        image: "https://www.changtrixget.com/wp-content/uploads/2018/09/superman-krypton-coaster.jpg",
        waitingTime: 3,
        size: 20,
        duration: 5,
        star: 12,
        rating: 5,
    },
    {
        id: "f56s4rt1fd",
        code: "CPE002",
        status: "open",
        name: "ชิงช้าสวรรค์",
        size: 50,
        duration: 10,
        star: 8,
        rating: 4,
    },
    {
        id: "bs6t42as42",
        code: "CPE003",
        status: "open",
        name: "บ้านผีสิง",
        size: 30,
        duration: 10,
        star: 8,
        rating: 4,
    },
    {
        id: "sb5te64a21",
        code: "CPE004",
        status: "open",
        name: "ปราสาทยักษ์",
        size: 30,
        duration: 10,
        star: 6,
        rating: 4,
    },
    {
        id: "srt6542xz1",
        code: "CPE005",
        status: "open",
        name: "ทอร์นาโด",
        size: 12,
        duration: 5,
        star: 6,
        rating: 3,
    },
    {
        id: "2d1ytn51a2",
        code: "CPE006",
        status: "open",
        name: "ท่องกาแล็กซี่",
        size: 10,
        duration: 8,
        star: 10,
        rating: 4,
    },
    {
        id: "5e41vbt4h8",
        code: "CPE007",
        status: "closed",
        name: "ทะยานเมฆา",
        size: 20,
        duration: 10,
        star: 10,
        rating: 4,
    },
    {
        id: "dn685t24d4",
        code: "CPE008",
        status: "temporarily closed",
        name: "ทะยานเมฆา",
        size: 20,
        duration: 10,
        star: 10,
        rating: 4,
    },
    {
        id: "s65rs4ma23",
        code: "CPE001",
        status: "open",
        name: "รถไฟเหาะ",
        image: "https://www.changtrixget.com/wp-content/uploads/2018/09/superman-krypton-coaster.jpg",
        waitingTime: 3,
        size: 20,
        duration: 5,
        star: 12,
        rating: 5,
    },
    {
        id: "f56s4rt1fd",
        code: "CPE002",
        status: "open",
        name: "ชิงช้าสวรรค์",
        size: 50,
        duration: 10,
        star: 8,
        rating: 4,
    },
    {
        id: "bs6t42as42",
        code: "CPE003",
        status: "open",
        name: "บ้านผีสิง",
        size: 30,
        duration: 10,
        star: 8,
        rating: 4,
    },
    {
        id: "sb5te64a21",
        code: "CPE004",
        status: "open",
        name: "ปราสาทยักษ์",
        size: 30,
        duration: 10,
        star: 6,
        rating: 4,
    },
    {
        id: "srt6542xz1",
        code: "CPE005",
        status: "open",
        name: "ทอร์นาโด",
        size: 12,
        duration: 5,
        star: 6,
        rating: 3,
    },
    {
        id: "2d1ytn51a2",
        code: "CPE006",
        status: "open",
        name: "ท่องกาแล็กซี่",
        size: 10,
        duration: 8,
        star: 10,
        rating: 4,
    },
    {
        id: "5e41vbt4h8",
        code: "CPE007",
        status: "closed",
        name: "ทะยานเมฆา",
        size: 20,
        duration: 10,
        star: 10,
        rating: 4,
    },
    {
        id: "dn685t24d4",
        code: "CPE008",
        status: "temporarily closed",
        name: "ทะยานเมฆา",
        size: 20,
        duration: 10,
        star: 10,
        rating: 4,
    },
]

export default ActivityData;